apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: csv-converter-image
  namespace: default
spec:
  tag: manshaehsan/blackhole
  serviceAccount: dockerhub
  builder:
    name: jng-builder
    kind: Builder
  source:
    git:
      url: https://github.com/manshaaazar/csv-converter
      revision: main
