apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: denouement
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/java
    - image: gcr.io/paketo-buildpacks/nodejs
    - image: gcr.io/paketo-buildpacks/go
