apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: jng-builder
  namespace: default
spec:
  serviceAccount: dockerhub
  tag: manshaehsan/blackhole
  stack:
    name: base
    kind: ClusterStack
  store:
    name: denouement
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/nodejs
    - group:
        - id: paketo-buildpacks/go
